cmake_path(GET CMAKE_CURRENT_LIST_DIR FILENAME ModName)
string(REPLACE " " "_" ModName ${ModName})

set(TGT ${ModName})
message("ModName: ${ModName}")

FILE(GLOB DIR_SRCS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
    "*.h"
    "*.cpp"
)

message("qt_add_library(\${TGT} STATIC")
    foreach(f ${DIR_SRCS})
    message("    \"${f}\"")
    endforeach()
message(")")

if (${QT_VERSION_MAJOR} LESS 6)
    add_library(${TGT}
        STATIC
        ${DIR_SRCS}
    )
else()
    qt_add_library(${TGT}
        STATIC
        ${DIR_SRCS}
    )
endif()


if (USE_QRC)

if(QT_VERSION VERSION_GREATER_EQUAL "6.2")
set(QSS_FILES
    "../stylesheet/dark/FluAmPmView.qss"
    "../stylesheet/dark/FluAppBarButton.qss"
    "../stylesheet/dark/FluAppBarToggleButton.qss"
    "../stylesheet/dark/FluAutoSuggestBox.qss"
    "../stylesheet/dark/FluBorder.qss"
    "../stylesheet/dark/FluBusyProgressRing.qss"
    "../stylesheet/dark/FluCalendarDatePicker.qss"
    "../stylesheet/dark/FluCalendarMonthView.qss"
    "../stylesheet/dark/FluCalendarSelectMonthView.qss"
    "../stylesheet/dark/FluCalendarSelectYearView.qss"
    "../stylesheet/dark/FluCalendarView.qss"
    "../stylesheet/dark/FluCalendarViewTitle.qss"
    "../stylesheet/dark/FluCalendarViewWeakTitle.qss"
    "../stylesheet/dark/FluCheckBox.qss"
    "../stylesheet/dark/FluCircleDot.qss"
    "../stylesheet/dark/FluCodeBox.qss"
    "../stylesheet/dark/FluColorButton.qss"
    "../stylesheet/dark/FluColorFlyout.qss"
    "../stylesheet/dark/FluColorLabel.qss"
    "../stylesheet/dark/FluColorPickerButton.qss"
    "../stylesheet/dark/FluColorView.qss"
    "../stylesheet/dark/FluComboBox.qss"
    "../stylesheet/dark/FluComboBoxEx.qss"
    "../stylesheet/dark/FluCommandBar.qss"
    "../stylesheet/dark/FluCommandBarIconItem.qss"
    "../stylesheet/dark/FluCommandBarIconTextItem.qss"
    "../stylesheet/dark/FluConfirmFlyout.qss"
    "../stylesheet/dark/FluDatePicker.qss"
    "../stylesheet/dark/FluDatePickerView.qss"
    "../stylesheet/dark/FluDialog.qss"
    "../stylesheet/dark/FluDisplayBox.qss"
    "../stylesheet/dark/FluDisplayBoxEx.qss"
    "../stylesheet/dark/FluDisplayIconBox.qss"
    "../stylesheet/dark/FluDockManager.qss"
    "../stylesheet/dark/FluDoubleSpinBox.qss"
    "../stylesheet/dark/FluDropDownButton.qss"
    "../stylesheet/dark/FluExpander.qss"
    "../stylesheet/dark/FluFlipView.qss"
    "../stylesheet/dark/FluFrameLessTitleBar.qss"
    "../stylesheet/dark/FluFWScrollView.qss"
    "../stylesheet/dark/FluGraphicalButton.qss"
    "../stylesheet/dark/FluHCard.qss"
    "../stylesheet/dark/FluHFlipView.qss"
    "../stylesheet/dark/FluHNavigationFlyIconTextItem.qss"
    "../stylesheet/dark/FluHNavigationIconTextItem.qss"
    "../stylesheet/dark/FluHNavigationMoreItem.qss"
    "../stylesheet/dark/FluHNavigationSettingsItem.qss"
    "../stylesheet/dark/FluHNavigationView.qss"
    "../stylesheet/dark/FluHScrollView.qss"
    "../stylesheet/dark/FluHomePageTitle.qss"
    "../stylesheet/dark/FluHSplitLine.qss"
    "../stylesheet/dark/FluHyperLinkButton.qss"
    "../stylesheet/dark/FluIconButton.qss"
    "../stylesheet/dark/FluInfoBadge.qss"
    "../stylesheet/dark/FluLabel.qss"
    "../stylesheet/dark/FluLineEdit.qss"
    "../stylesheet/dark/FluListView.qss"
    "../stylesheet/dark/FluLoopView.qss"
    "../stylesheet/dark/FluMenu.qss"
    "../stylesheet/dark/FluMenuBar.qss"
    "../stylesheet/dark/FluMenuBarItem.qss"
    "../stylesheet/dark/FluMessageBox.qss"
    "../stylesheet/dark/FluMSNavigationItem.qss"
    "../stylesheet/dark/FluMSNavigationView.qss"
    "../stylesheet/dark/FluMSPage.qss"
    "../stylesheet/dark/FluMSWindow.qss"
    "../stylesheet/dark/FluNavigationItem.qss"
    "../stylesheet/dark/FluPagination.qss"
    "../stylesheet/dark/FluPaginationItem.qss"
    "../stylesheet/dark/FluPasswordBox.qss"
    "../stylesheet/dark/FluPivot.qss"
    "../stylesheet/dark/FluPivotTitleBar.qss"
    "../stylesheet/dark/FluPivotTitleBarItem.qss"
    "../stylesheet/dark/FluPushButton.qss"
    "../stylesheet/dark/FluRadioButton.qss"
    "../stylesheet/dark/FluRatingControl.qss"
    "../stylesheet/dark/FluRepeatButton.qss"
    "../stylesheet/dark/FluRotationButton.qss"
    "../stylesheet/dark/FluRoundMenu.qss"
    "../stylesheet/dark/FluRoundMenuView.qss"
    "../stylesheet/dark/FluScrollBar.qss"
    "../stylesheet/dark/FluSearchLineEdit.qss"
    "../stylesheet/dark/FluSegmented.qss"
    "../stylesheet/dark/FluSegmentedItem.qss"
    "../stylesheet/dark/FluSettingsLabelBox.qss"
    "../stylesheet/dark/FluSettingsSelectBox.qss"
    "../stylesheet/dark/FluSettingsVersionBox.qss"
    "../stylesheet/dark/FluShortInfoBar.qss"
    "../stylesheet/dark/FluShortcutPicker.qss"
    "../stylesheet/dark/FluShortcutPickerDlg.qss"
    "../stylesheet/dark/FluSlider.qss"
    "../stylesheet/dark/FluSpinBox.qss"
    "../stylesheet/dark/FluSplitButton.qss"
    "../stylesheet/dark/FluStyleButton.qss"
    "../stylesheet/dark/FluTabBar.qss"
    "../stylesheet/dark/FluTabBarContent.qss"
    "../stylesheet/dark/FluTabBarItem.qss"
    "../stylesheet/dark/FluTableView.qss"
    "../stylesheet/dark/FluTabView.qss"
    "../stylesheet/dark/FluTabWidget.qss"
    "../stylesheet/dark/FluTerminalWidget.qss"
    "../stylesheet/dark/FluTextEdit.qss"
    "../stylesheet/dark/FluTimePicker24H.qss"
    "../stylesheet/dark/FluTimePicker24HView.qss"
    "../stylesheet/dark/FluTimePickerAP.qss"
    "../stylesheet/dark/FluTimePickerAPView.qss"
    "../stylesheet/dark/FluToggleButton.qss"
    "../stylesheet/dark/FluToggleSwitch.qss"
    "../stylesheet/dark/FluToggleSwitchEx.qss"
    "../stylesheet/dark/FluTreeView.qss"
    "../stylesheet/dark/FluVCard.qss"
    "../stylesheet/dark/FluVFlipView.qss"
    "../stylesheet/dark/FluVFlyout.qss"
    "../stylesheet/dark/FluVNavigationFlyIconTextItem.qss"
    "../stylesheet/dark/FluVNavigationIconTextItem.qss"
    "../stylesheet/dark/FluVNavigationMenuItem.qss"
    "../stylesheet/dark/FluVNavigationSearchItem.qss"
    "../stylesheet/dark/FluVNavigationSettingsItem.qss"
    "../stylesheet/dark/FluVNavigationView.qss"
    "../stylesheet/dark/FluVRadioGroupBox.qss"
    "../stylesheet/dark/FluVScrollView.qss"
    "../stylesheet/dark/FluVSplitLine.qss"
    # "../stylesheet/dark/FluWindowkitButton.qss"
    "../stylesheet/dark/FluWindowKitTitleBar.qss"
    "../stylesheet/dark/FluWindowKitWidget.qss"
    "../stylesheet/dark/FluWindowKitWindow.qss"
    "../stylesheet/light/FluAmPmView.qss"
    "../stylesheet/light/FluAppBarButton.qss"
    "../stylesheet/light/FluAppBarToggleButton.qss"
    "../stylesheet/light/FluAutoSuggestBox.qss"
    "../stylesheet/light/FluBorder.qss"
    "../stylesheet/light/FluBusyProgressRing.qss"
    "../stylesheet/light/FluCalendarDatePicker.qss"
    "../stylesheet/light/FluCalendarMonthView.qss"
    "../stylesheet/light/FluCalendarSelectMonthView.qss"
    "../stylesheet/light/FluCalendarSelectYearView.qss"
    "../stylesheet/light/FluCalendarView.qss"
    "../stylesheet/light/FluCalendarViewTitle.qss"
    "../stylesheet/light/FluCalendarViewWeakTitle.qss"
    "../stylesheet/light/FluCheckBox.qss"
    "../stylesheet/light/FluCircleDot.qss"
    "../stylesheet/light/FluCodeBox.qss"
    "../stylesheet/light/FluColorButton.qss"
    "../stylesheet/light/FluColorFlyout.qss"
    "../stylesheet/light/FluColorLabel.qss"
    "../stylesheet/light/FluColorPickerButton.qss"
    "../stylesheet/light/FluColorView.qss"
    "../stylesheet/light/FluComboBox.qss"
    "../stylesheet/light/FluComboBoxEx.qss"
    "../stylesheet/light/FluCommandBar.qss"
    "../stylesheet/light/FluCommandBarIconItem.qss"
    "../stylesheet/light/FluCommandBarIconTextItem.qss"
    "../stylesheet/light/FluConfirmFlyout.qss"
    "../stylesheet/light/FluDatePicker.qss"
    "../stylesheet/light/FluDatePickerView.qss"
    "../stylesheet/light/FluDialog.qss"
    "../stylesheet/light/FluDisplayBox.qss"
    "../stylesheet/light/FluDisplayBoxEx.qss"
    "../stylesheet/light/FluDisplayIconBox.qss"
    "../stylesheet/light/FluDockManager.qss"
    "../stylesheet/light/FluDoubleSpinBox.qss"
    "../stylesheet/light/FluDropDownButton.qss"
    "../stylesheet/light/FluExpander.qss"
    "../stylesheet/light/FluFrameLessTitleBar.qss"
    "../stylesheet/light/FluFWScrollView.qss"
    "../stylesheet/light/FluGraphicalButton.qss"
    "../stylesheet/light/FluHCard.qss"
    "../stylesheet/light/FluHFlipView.qss"
    "../stylesheet/light/FluHNavigationFlyIconTextItem.qss"
    "../stylesheet/light/FluHNavigationIconTextItem.qss"
    "../stylesheet/light/FluHNavigationMoreItem.qss"
    "../stylesheet/light/FluHNavigationSettingsItem.qss"
    "../stylesheet/light/FluHNavigationView.qss"
    "../stylesheet/light/FluHomePageTitle.qss"
    "../stylesheet/light/FluHScrollView.qss"
    "../stylesheet/light/FluHSplitLine.qss"
    "../stylesheet/light/FluHyperLinkButton.qss"
    "../stylesheet/light/FluIconButton.qss"
    "../stylesheet/light/FluInfoBadge.qss"
    "../stylesheet/light/FluLabel.qss"
    "../stylesheet/light/FluLineEdit.qss"
    "../stylesheet/light/FluListView.qss"
    "../stylesheet/light/FluLoopView.qss"
    "../stylesheet/light/FluMenu.qss"
    "../stylesheet/light/FluMenuBar.qss"
    "../stylesheet/light/FluMenuBarItem.qss"
    "../stylesheet/light/FluMessageBox.qss"
    "../stylesheet/light/FluMSNavigationItem.qss"
    "../stylesheet/light/FluMSNavigationView.qss"
    "../stylesheet/light/FluMSPage.qss"
    "../stylesheet/light/FluMSWindow.qss"
    "../stylesheet/light/FluNavigationItem.qss"
    "../stylesheet/light/FluPagination.qss"
    "../stylesheet/light/FluPaginationItem.qss"
    "../stylesheet/light/FluPasswordBox.qss"
    "../stylesheet/light/FluPivot.qss"
    "../stylesheet/light/FluPivotTitleBar.qss"
    "../stylesheet/light/FluPivotTitleBarItem.qss"
    "../stylesheet/light/FluPPushButton.qss"
    "../stylesheet/light/FluProgressBar.qss"
    "../stylesheet/light/FluPushButton.qss"
    "../stylesheet/light/FluRadioButton.qss"
    "../stylesheet/light/FluRatingControl.qss"
    "../stylesheet/light/FluRepeatButton.qss"
    "../stylesheet/light/FluRotationButton.qss"
    "../stylesheet/light/FluRoundMenu.qss"
    "../stylesheet/light/FluRoundMenuView.qss"
    "../stylesheet/light/FluScrollBar.qss"
    "../stylesheet/light/FluSearchLineEdit.qss"
    "../stylesheet/light/FluSegmented.qss"
    "../stylesheet/light/FluSegmentedItem.qss"
    "../stylesheet/light/FluSettingsLabelBox.qss"
    "../stylesheet/light/FluSettingsSelectBox.qss"
    "../stylesheet/light/FluSettingsVersionBox.qss"
    "../stylesheet/light/FluShortInfoBar.qss"
    "../stylesheet/light/FluShortcutPicker.qss"
    "../stylesheet/light/FluShortcutPickerDlg.qss"
    "../stylesheet/light/FluSlider.qss"
    "../stylesheet/light/FluSpinBox.qss"
    "../stylesheet/light/FluSplitButton.qss"
    "../stylesheet/light/FluStyleButton.qss"
    "../stylesheet/light/FluTabBar.qss"
    "../stylesheet/light/FluTabBarContent.qss"
    "../stylesheet/light/FluTabBarItem.qss"
    "../stylesheet/light/FluTableView.qss"
    "../stylesheet/light/FluTabView.qss"
    "../stylesheet/light/FluTabWidget.qss"
    "../stylesheet/light/FluTerminalWidget.qss"
    "../stylesheet/light/FluTextEdit.qss"
    "../stylesheet/light/FluTimePicker24H.qss"
    "../stylesheet/light/FluTimePicker24HView.qss"
    "../stylesheet/light/FluTimePickerAP.qss"
    "../stylesheet/light/FluTimePickerAPView.qss"
    "../stylesheet/light/FluToggleButton.qss"
    "../stylesheet/light/FluToggleSwitch.qss"
    "../stylesheet/light/FluToggleSwitchEx.qss"
    "../stylesheet/light/FluTreeView.qss"
    "../stylesheet/light/FluVCard.qss"
    "../stylesheet/light/FluVFlipView.qss"
    "../stylesheet/light/FluVFlyout.qss"
    "../stylesheet/light/FluVNavigationFlyIconTextItem.qss"
    "../stylesheet/light/FluVNavigationIconTextItem.qss"
    "../stylesheet/light/FluVNavigationMenuItem.qss"
    "../stylesheet/light/FluVNavigationSearchItem.qss"
    "../stylesheet/light/FluVNavigationSettingsItem.qss"
    "../stylesheet/light/FluVNavigationView.qss"
    "../stylesheet/light/FluVRadioGroupBox.qss"
    "../stylesheet/light/FluVScrollView.qss"
    "../stylesheet/light/FluVSplitLine.qss"
    # "../stylesheet/light/FluWindowkitButton.qss"
    "../stylesheet/light/FluWindowKitTitleBar.qss"
    "../stylesheet/light/FluWindowKitWidget.qss"
    "../stylesheet/light/FluWindowKitWindow.qss"
    "../stylesheet/dark/FluThemeButton.qss"
    "../stylesheet/light/FluThemeButton.qss"
    "../stylesheet/atomOneDark/FluThemeButton.qss"
    "../stylesheet/atomOneDark/FluAmPmView.qss"
    "../stylesheet/atomOneDark/FluAppBarButton.qss"
    "../stylesheet/atomOneDark/FluAppBarToggleButton.qss"
    "../stylesheet/atomOneDark/FluAutoSuggestBox.qss"
    "../stylesheet/atomOneDark/FluBorder.qss"
    "../stylesheet/atomOneDark/FluBusyProgressRing.qss"
    "../stylesheet/atomOneDark/FluCalendarDatePicker.qss"
    "../stylesheet/atomOneDark/FluCalendarMonthView.qss"
    "../stylesheet/atomOneDark/FluCalendarSelectMonthView.qss"
    "../stylesheet/atomOneDark/FluCalendarSelectYearView.qss"
    "../stylesheet/atomOneDark/FluCalendarView.qss"
    "../stylesheet/atomOneDark/FluCalendarViewTitle.qss"
    "../stylesheet/atomOneDark/FluCalendarViewWeakTitle.qss"
    "../stylesheet/atomOneDark/FluCheckBox.qss"
    "../stylesheet/atomOneDark/FluCircleDot.qss"
    "../stylesheet/atomOneDark/FluCodeBox.qss"
    "../stylesheet/atomOneDark/FluColorButton.qss"
    "../stylesheet/atomOneDark/FluColorFlyout.qss"
    "../stylesheet/atomOneDark/FluColorLabel.qss"
    "../stylesheet/atomOneDark/FluColorPickerButton.qss"
    "../stylesheet/atomOneDark/FluColorView.qss"
    "../stylesheet/atomOneDark/FluComboBox.qss"
    "../stylesheet/atomOneDark/FluComboBoxEx.qss"
    "../stylesheet/atomOneDark/FluCommandBar.qss"
    "../stylesheet/atomOneDark/FluCommandBarIconItem.qss"
    "../stylesheet/atomOneDark/FluCommandBarIconTextItem.qss"
    "../stylesheet/atomOneDark/FluConfirmFlyout.qss"
    "../stylesheet/atomOneDark/FluDatePicker.qss"
    "../stylesheet/atomOneDark/FluDatePickerView.qss"
    "../stylesheet/atomOneDark/FluDialog.qss"
    "../stylesheet/atomOneDark/FluDisplayBox.qss"
    "../stylesheet/atomOneDark/FluDisplayBoxEx.qss"
    "../stylesheet/atomOneDark/FluDisplayIconBox.qss"
    "../stylesheet/atomOneDark/FluDockManager.qss"
    "../stylesheet/atomOneDark/FluDoubleSpinBox.qss"
    "../stylesheet/atomOneDark/FluDropDownButton.qss"
    "../stylesheet/atomOneDark/FluExpander.qss"
    "../stylesheet/atomOneDark/FluFrameLessTitleBar.qss"
    "../stylesheet/atomOneDark/FluFWScrollView.qss"
    "../stylesheet/atomOneDark/FluGraphicalButton.qss"
    "../stylesheet/atomOneDark/FluHCard.qss"
    "../stylesheet/atomOneDark/FluHFlipView.qss"
    "../stylesheet/atomOneDark/FluHNavigationFlyIconTextItem.qss"
    "../stylesheet/atomOneDark/FluHNavigationIconTextItem.qss"
    "../stylesheet/atomOneDark/FluHNavigationMoreItem.qss"
    "../stylesheet/atomOneDark/FluHNavigationSettingsItem.qss"
    "../stylesheet/atomOneDark/FluHNavigationView.qss"
    "../stylesheet/atomOneDark/FluHomePageTitle.qss"
    "../stylesheet/atomOneDark/FluHScrollView.qss"
    "../stylesheet/atomOneDark/FluHSplitLine.qss"
    "../stylesheet/atomOneDark/FluHyperLinkButton.qss"
    "../stylesheet/atomOneDark/FluIconButton.qss"
    "../stylesheet/atomOneDark/FluInfoBadge.qss"
    "../stylesheet/atomOneDark/FluLabel.qss"
    "../stylesheet/atomOneDark/FluLineEdit.qss"
    "../stylesheet/atomOneDark/FluListView.qss"
    "../stylesheet/atomOneDark/FluLoopView.qss"
    "../stylesheet/atomOneDark/FluMainWidgetDemo.qss"
    "../stylesheet/atomOneDark/FluMenu.qss"
    "../stylesheet/atomOneDark/FluMenuBar.qss"
    "../stylesheet/atomOneDark/FluMenuBarItem.qss"
    "../stylesheet/atomOneDark/FluMenuDemo.qss"
    "../stylesheet/atomOneDark/FluMessageBox.qss"
    "../stylesheet/atomOneDark/FluMSNavigationItem.qss"
    "../stylesheet/atomOneDark/FluMSNavigationView.qss"
    "../stylesheet/atomOneDark/FluMSPage.qss"
    "../stylesheet/atomOneDark/FluMSWindow.qss"
    "../stylesheet/atomOneDark/FluNavigationItem.qss"
    "../stylesheet/atomOneDark/FluPagination.qss"
    "../stylesheet/atomOneDark/FluPaginationItem.qss"
    "../stylesheet/atomOneDark/FluPasswordBox.qss"
    "../stylesheet/atomOneDark/FluPivot.qss"
    "../stylesheet/atomOneDark/FluPivotTitleBar.qss"
    "../stylesheet/atomOneDark/FluPivotTitleBarItem.qss"
    "../stylesheet/atomOneDark/FluProgressBar.qss"
    "../stylesheet/atomOneDark/FluPushButton.qss"
    "../stylesheet/atomOneDark/FluRadioButton.qss"
    "../stylesheet/atomOneDark/FluRatingControl.qss"
    "../stylesheet/atomOneDark/FluRepeatButton.qss"
    "../stylesheet/atomOneDark/FluRotationButton.qss"
    "../stylesheet/atomOneDark/FluRoundMenu.qss"
    "../stylesheet/atomOneDark/FluRoundMenuView.qss"
    "../stylesheet/atomOneDark/FluScrollBar.qss"
    "../stylesheet/atomOneDark/FluSearchLineEdit.qss"
    "../stylesheet/atomOneDark/FluSegmented.qss"
    "../stylesheet/atomOneDark/FluSegmentedItem.qss"
    "../stylesheet/atomOneDark/FluSettingsLabelBox.qss"
    "../stylesheet/atomOneDark/FluSettingsSelectBox.qss"
    "../stylesheet/atomOneDark/FluSettingsVersionBox.qss"
    "../stylesheet/atomOneDark/FluShortInfoBar.qss"
    "../stylesheet/atomOneDark/FluShortcutPicker.qss"
    "../stylesheet/atomOneDark/FluShortcutPickerDlg.qss"
    "../stylesheet/atomOneDark/FluSlider.qss"
    "../stylesheet/atomOneDark/FluSpinBox.qss"
    "../stylesheet/atomOneDark/FluSplitButton.qss"
    "../stylesheet/atomOneDark/FluStyleButton.qss"
    "../stylesheet/atomOneDark/FluTabBar.qss"
    "../stylesheet/atomOneDark/FluTabBarContent.qss"
    "../stylesheet/atomOneDark/FluTabBarItem.qss"
    "../stylesheet/atomOneDark/FluTableView.qss"
    "../stylesheet/atomOneDark/FluTabView.qss"
    "../stylesheet/atomOneDark/FluTabWidget.qss"
    "../stylesheet/atomOneDark/FluTerminalWidget.qss"
    "../stylesheet/atomOneDark/FluTextEdit.qss"
    "../stylesheet/atomOneDark/FluTimePicker24H.qss"
    "../stylesheet/atomOneDark/FluTimePicker24HView.qss"
    "../stylesheet/atomOneDark/FluTimePickerAP.qss"
    "../stylesheet/atomOneDark/FluTimePickerAPView.qss"
    "../stylesheet/atomOneDark/FluToggleButton.qss"
    "../stylesheet/atomOneDark/FluToggleSwitch.qss"
    "../stylesheet/atomOneDark/FluToggleSwitchEx.qss"
    "../stylesheet/atomOneDark/FluTreeView.qss"
    "../stylesheet/atomOneDark/FluVCard.qss"
    "../stylesheet/atomOneDark/FluVFlipView.qss"
    "../stylesheet/atomOneDark/FluVFlyout.qss"
    "../stylesheet/atomOneDark/FluVNavigationFlyIconTextItem.qss"
    "../stylesheet/atomOneDark/FluVNavigationIconTextItem.qss"
    "../stylesheet/atomOneDark/FluVNavigationMenuItem.qss"
    "../stylesheet/atomOneDark/FluVNavigationSearchItem.qss"
    "../stylesheet/atomOneDark/FluVNavigationSettingsItem.qss"
    "../stylesheet/atomOneDark/FluVNavigationView.qss"
    "../stylesheet/atomOneDark/FluVRadioGroupBox.qss"
    "../stylesheet/atomOneDark/FluVScrollView.qss"
    "../stylesheet/atomOneDark/FluVSplitLine.qss"
    # "../stylesheet/atomOneDark/FluWindowkitButton.qss"
    "../stylesheet/atomOneDark/FluWindowKitTitleBar.qss"
    "../stylesheet/atomOneDark/FluWindowKitWidget.qss"
    "../stylesheet/atomOneDark/FluWindowKitWindow.qss"
    "../stylesheet/atomOneDark/FluPPushButton.qss"
    "../stylesheet/dark/FluPPushButton.qss"
    "../stylesheet/light/FluScaleButton.qss"
    "../stylesheet/atomOneDark/FluScaleButton.qss"
    "../stylesheet/dark/FluScaleButton.qss"
    "../stylesheet/light/FluPMenuBar.qss"
    "../stylesheet/atomOneDark/FluPMenuBar.qss"
    "../stylesheet/dark/FluPMenuBar.qss"
    "../stylesheet/light/FluPMenu.qss"
    "../stylesheet/atomOneDark/FluPMenu.qss"
    "../stylesheet/dark/FluPMenu.qss"
)
source_group(TREE ${CMAKE_SOURCE_DIR} FILES ${QSS_FILES})

qt_add_resources(${TGT} "ControlsQss"
PREFIX "/"
BASE ".."
FILES
${QSS_FILES}
)
flu_qrc_lowopt(ControlsQss)

set(RES_FILES
    "../res/badgelogo.scale-100.png"
    "../res/badgelogo.scale-140.png"
    "../res/badgelogo.scale-180.png"
    "../res/blank.png"
    "../res/ChevronDown.png"
    "../res/ChevronRight.png"
    "../res/ChromeClose.png"
    "../res/CoffeeCup.png"
    "../res/Contacts.txt"
    "../res/ControlImages/Acrylic.png"
    "../res/ControlImages/AnimatedIcon.png"
    "../res/ControlImages/AnimatedVisualPlayer.png"
    "../res/ControlImages/AnimationInterop.png"
    "../res/ControlImages/AnnotatedScrollBar.png"
    "../res/ControlImages/AppBarButton.png"
    "../res/ControlImages/AppBarSeparator.png"
    "../res/ControlImages/AppBarToggleButton.png"
    "../res/ControlImages/AutomationProperties.png"
    "../res/ControlImages/AutoSuggestBox.png"
    "../res/ControlImages/Border.png"
    "../res/ControlImages/BreadcrumbBar.png"
    "../res/ControlImages/Button.png"
    "../res/ControlImages/CalendarDatePicker.png"
    "../res/ControlImages/CalendarView.png"
    "../res/ControlImages/Canvas.png"
    "../res/ControlImages/Checkbox.png"
    "../res/ControlImages/Clipboard.png"
    "../res/ControlImages/ColorPaletteResources.png"
    "../res/ControlImages/ColorPicker.png"
    "../res/ControlImages/ComboBox.png"
    "../res/ControlImages/CommandBar.png"
    "../res/ControlImages/CommandBarFlyout.png"
    "../res/ControlImages/CompactSizing.png"
    "../res/ControlImages/ConnectedAnimation.png"
    "../res/ControlImages/ContentDialog.png"
    "../res/ControlImages/CreateMultipleWindows.png"
    "../res/ControlImages/DataGrid.png"
    "../res/ControlImages/DatePicker.png"
    "../res/ControlImages/DropDownButton.png"
    "../res/ControlImages/EasingFunction.png"
    "../res/ControlImages/Expander.png"
    "../res/ControlImages/FilePicker.png"
    "../res/ControlImages/FlipView.png"
    "../res/ControlImages/Flyout.png"
    "../res/ControlImages/Grid.png"
    "../res/ControlImages/GridView.png"
    "../res/ControlImages/HyperlinkButton.png"
    "../res/ControlImages/IconElement.png"
    "../res/ControlImages/Image.png"
    "../res/ControlImages/ImplicitTransition.png"
    "../res/ControlImages/InfoBadge.png"
    "../res/ControlImages/InfoBar.png"
    "../res/ControlImages/InkCanvas.png"
    "../res/ControlImages/InkToolbar.png"
    "../res/ControlImages/InputValidation.png"
    "../res/ControlImages/ItemsRepeater.png"
    "../res/ControlImages/ItemsView.png"
    "../res/ControlImages/Line.png"
    "../res/ControlImages/ListBox.png"
    "../res/ControlImages/ListView.png"
    "../res/ControlImages/MediaPlayerElement.png"
    "../res/ControlImages/MenuBar.png"
    "../res/ControlImages/MenuFlyout.png"
    "../res/ControlImages/NavigationView.png"
    "../res/ControlImages/NumberBox.png"
    "../res/ControlImages/PageTransition.png"
    "../res/ControlImages/ParallaxView.png"
    "../res/ControlImages/PasswordBox.png"
    "../res/ControlImages/PersonPicture.png"
    "../res/ControlImages/PipsPager.png"
    "../res/ControlImages/Pivot.png"
    "../res/ControlImages/Placeholder.png"
    "../res/ControlImages/ProgressBar.png"
    "../res/ControlImages/ProgressRing.png"
    "../res/ControlImages/PullToRefresh.png"
    "../res/ControlImages/RadialGradientBrush.png"
    "../res/ControlImages/RadioButton.png"
    "../res/ControlImages/RadioButtons.png"
    "../res/ControlImages/RatingControl.png"
    "../res/ControlImages/RelativePanel.png"
    "../res/ControlImages/RepeatButton.png"
    "../res/ControlImages/RevealFocus.png"
    "../res/ControlImages/RichEditBox.png"
    "../res/ControlImages/RichTextBlock.png"
    "../res/ControlImages/ScrollView.png"
    "../res/ControlImages/ScrollViewer.png"
    "../res/ControlImages/SemanticZoom.png"
    "../res/ControlImages/Shape.png"
    "../res/ControlImages/Slider.png"
    "../res/ControlImages/Sound.png"
    "../res/ControlImages/SplitButton.png"
    "../res/ControlImages/SplitView.png"
    "../res/ControlImages/StackPanel.png"
    "../res/ControlImages/StandardUICommand.png"
    "../res/ControlImages/SwipeControl.png"
    "../res/ControlImages/TabView.png"
    "../res/ControlImages/TeachingTip.png"
    "../res/ControlImages/TextBlock.png"
    "../res/ControlImages/TextBox.png"
    "../res/ControlImages/ThemeTransition.png"
    "../res/ControlImages/TimePicker.png"
    "../res/ControlImages/TitleBar.png"
    "../res/ControlImages/ToggleButton.png"
    "../res/ControlImages/ToggleSplitButton.png"
    "../res/ControlImages/ToggleSwitch.png"
    "../res/ControlImages/ToolTip.png"
    "../res/ControlImages/TreeView.png"
    "../res/ControlImages/VariableSizedWrapGrid.png"
    "../res/ControlImages/Viewbox.png"
    "../res/ControlImages/WebView.png"
    "../res/ControlImages/XamlUICommand.png"
    "../res/ControlResImages/CheckBox-Black.png"
    "../res/ControlResImages/CheckBox-White.png"
    "../res/ControlResImages/CheckBoxPressed-Black.png"
    "../res/ControlResImages/CheckBoxPressed-White.png"
    "../res/ControlResImages/ChevronDown-Dark.png"
    "../res/ControlResImages/ChevronDown-Light.png"
    "../res/ControlResImages/ChevronRight-Light.png"
    "../res/ControlResImages/RadioButton-Black.png"
    "../res/ControlResImages/RadioButton-White.png"
    "../res/ControlResImages/RadioButtonHover-Black.png"
    "../res/ControlResImages/RadioButtonHover-White.png"
    "../res/ControlResImages/RadioButtonPressed-Black.png"
    "../res/ControlResImages/RadioButtonPressed-White.png"
    "../res/ControlResImages/SpinBoxDown-Dark.png"
    "../res/ControlResImages/SpinBoxDown-Light.png"
    "../res/ControlResImages/SpinBoxDownDisabled-Dark.png"
    "../res/ControlResImages/SpinBoxDownDisabled-Light.png"
    "../res/ControlResImages/SpinBoxUp-Dark.png"
    "../res/ControlResImages/SpinBoxUp-Light.png"
    "../res/ControlResImages/SpinBoxUpDisabled-Dark.png"
    "../res/ControlResImages/SpinBoxUpDisabled-Light.png"
    "../res/ControlResImages/ToggleSwitchDisabled-Dark.png"
    "../res/ControlResImages/ToggleSwitchDisabled-light.png"
    "../res/ControlResImages/ToggleSwitchOff-Dark.png"
    "../res/ControlResImages/ToggleSwitchOff-light.png"
    "../res/ControlResImages/ToggleSwitchOffHover-Dark.png"
    "../res/ControlResImages/ToggleSwitchOffHover-light.png"
    "../res/ControlResImages/ToggleSwitchOffPressed-Dark.png"
    "../res/ControlResImages/ToggleSwitchOffPressed-light.png"
    "../res/ControlResImages/ToggleSwitchOn-Dark.png"
    "../res/ControlResImages/ToggleSwitchOn-light.png"
    "../res/ControlResImages/ToggleSwitchOnHover-Dark.png"
    "../res/ControlResImages/ToggleSwitchOnHover-light.png"
    "../res/ControlResImages/ToggleSwitchOnPressed-Dark.png"
    "../res/ControlResImages/ToggleSwitchOnPressed-light.png"
    "../res/CopyLinkTeachingTip.png"
    "../res/folder.png"
    "../res/GalleryHeaderImage.png"
    "../res/HomeHeaderTiles/github-mark-white.png"
    "../res/HomeHeaderTiles/github-mark-white.svg"
    "../res/HomeHeaderTiles/github-mark.png"
    "../res/HomeHeaderTiles/github-mark.svg"
    "../res/HomeHeaderTiles/Header-Store.dark.png"
    "../res/HomeHeaderTiles/Header-Store.light.png"
    "../res/HomeHeaderTiles/Header-Toolkit.png"
    "../res/HomeHeaderTiles/Header-WindowsDesign.png"
    "../res/HomeHeaderTiles/Header-WinUIGallery.png"
    "../res/LottieLogo1.png"
    "../res/ninegrid.gif"
    "../res/SampleMedia/cliff.jpg"
    "../res/SampleMedia/fishes.wmv"
    "../res/SampleMedia/grapes.jpg"
    "../res/SampleMedia/ladybug.wmv"
    "../res/SampleMedia/LandscapeImage1.jpg"
    "../res/SampleMedia/LandscapeImage10.jpg"
    "../res/SampleMedia/LandscapeImage11.jpg"
    "../res/SampleMedia/LandscapeImage12.jpg"
    "../res/SampleMedia/LandscapeImage13.jpg"
    "../res/SampleMedia/LandscapeImage2.jpg"
    "../res/SampleMedia/LandscapeImage3.jpg"
    "../res/SampleMedia/LandscapeImage4.jpg"
    "../res/SampleMedia/LandscapeImage5.jpg"
    "../res/SampleMedia/LandscapeImage6.jpg"
    "../res/SampleMedia/LandscapeImage7.jpg"
    "../res/SampleMedia/LandscapeImage8.jpg"
    "../res/SampleMedia/LandscapeImage9.jpg"
    "../res/SampleMedia/MirrorPCConsent.svg"
    "../res/SampleMedia/rainier.jpg"
    "../res/SampleMedia/sunset.jpg"
    "../res/SampleMedia/treetops.jpg"
    "../res/SampleMedia/valley.jpg"
    "../res/ScrollBottom.png"
    "../res/ScrollTop.png"
    "../res/Slices.png"
    "../res/Slices2.png"
    "../res/SunBlack.png"
    "../res/SunWhite.png"
    "../res/TabViewIcons/cmd.png"
    "../res/TabViewIcons/linux.png"
    "../res/TabViewIcons/powershell.png"
    "../res/Tiles/BadgeLogo.scale-100.png"
    "../res/Tiles/BadgeLogo.scale-125.png"
    "../res/Tiles/BadgeLogo.scale-150.png"
    "../res/Tiles/BadgeLogo.scale-200.png"
    "../res/Tiles/BadgeLogo.scale-400.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.scale-100_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.scale-125_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.scale-150_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.scale-200_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.scale-400_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-16_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-16_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-20_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-20_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-24_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-24_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-256_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-256_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-30_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-30_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-32_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-32_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-36_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-36_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-40_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-40_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-48_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-48_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-60_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-60_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-64_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-64_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-72_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-72_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-80_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-80_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-96_altform-unplated_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryAppList.targetsize-96_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryBadgeLogo.scale-100_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryBadgeLogo.scale-125_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryBadgeLogo.scale-150_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryBadgeLogo.scale-200_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryBadgeLogo.scale-400_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryLargeTile.scale-100_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryLargeTile.scale-125_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryLargeTile.scale-150_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryLargeTile.scale-200_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryLargeTile.scale-400_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryMedTile.scale-100_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryMedTile.scale-125_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryMedTile.scale-150_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryMedTile.scale-200_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryMedTile.scale-400_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySmallTile.scale-100_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySmallTile.scale-125_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySmallTile.scale-150_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySmallTile.scale-200_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySmallTile.scale-400_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySplashScreen.scale-100_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySplashScreen.scale-125_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySplashScreen.scale-150_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySplashScreen.scale-200_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGallerySplashScreen.scale-400_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryStoreLogo.scale-100_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryStoreLogo.scale-125_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryStoreLogo.scale-150_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryStoreLogo.scale-200_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryStoreLogo.scale-400_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryWideTile.scale-100_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryWideTile.scale-125_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryWideTile.scale-150_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryWideTile.scale-200_contrast-black.png"
    "../res/Tiles/contrast-black/XAMLControlsGalleryWideTile.scale-400_contrast-black.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.scale-100_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.scale-125_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.scale-150_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.scale-200_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.scale-400_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-16_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-16_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-20_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-20_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-24_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-24_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-256_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-256_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-30_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-30_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-32_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-32_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-36_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-36_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-40_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-40_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-48_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-48_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-60_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-60_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-64_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-64_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-72_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-72_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-80_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-80_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-96_altform-unplated_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryAppList.targetsize-96_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryBadgeLogo.scale-100_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryBadgeLogo.scale-125_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryBadgeLogo.scale-150_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryBadgeLogo.scale-200_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryBadgeLogo.scale-400_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryLargeTile.scale-100_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryLargeTile.scale-125_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryLargeTile.scale-150_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryLargeTile.scale-200_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryLargeTile.scale-400_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryMedTile.scale-100_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryMedTile.scale-125_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryMedTile.scale-150_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryMedTile.scale-200_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryMedTile.scale-400_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySmallTile.scale-100_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySmallTile.scale-125_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySmallTile.scale-150_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySmallTile.scale-200_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySmallTile.scale-400_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySplashScreen.scale-100_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySplashScreen.scale-125_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySplashScreen.scale-150_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySplashScreen.scale-200_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGallerySplashScreen.scale-400_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryStoreLogo.scale-100_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryStoreLogo.scale-125_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryStoreLogo.scale-150_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryStoreLogo.scale-200_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryStoreLogo.scale-400_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryWideTile.scale-100_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryWideTile.scale-125_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryWideTile.scale-150_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryWideTile.scale-200_contrast-white.png"
    "../res/Tiles/contrast-white/XAMLControlsGalleryWideTile.scale-400_contrast-white.png"
    "../res/Tiles/GalleryIcon.ico"
    "../res/Tiles/LargeTile.scale-100.png"
    "../res/Tiles/LargeTile.scale-125.png"
    "../res/Tiles/LargeTile.scale-150.png"
    "../res/Tiles/LargeTile.scale-200.png"
    "../res/Tiles/LargeTile.scale-400.png"
    "../res/Tiles/SmallTile-sdk.altform-lightunplated_targetsize-16.png"
    "../res/Tiles/SmallTile-sdk.altform-lightunplated_targetsize-24.png"
    "../res/Tiles/SmallTile-sdk.altform-lightunplated_targetsize-256.png"
    "../res/Tiles/SmallTile-sdk.altform-lightunplated_targetsize-32.png"
    "../res/Tiles/SmallTile-sdk.altform-lightunplated_targetsize-48.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-16.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-20.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-24.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-256.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-30.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-32.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-36.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-40.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-48.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-60.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-64.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-72.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-80.png"
    "../res/Tiles/SmallTile-sdk.altform-unplated_targetsize-96.png"
    "../res/Tiles/SmallTile-sdk.scale-100.png"
    "../res/Tiles/SmallTile-sdk.scale-125.png"
    "../res/Tiles/SmallTile-sdk.scale-150.png"
    "../res/Tiles/SmallTile-sdk.scale-200.png"
    "../res/Tiles/SmallTile-sdk.scale-400.png"
    "../res/Tiles/SmallTile-sdk.targetsize-16.png"
    "../res/Tiles/SmallTile-sdk.targetsize-20.png"
    "../res/Tiles/SmallTile-sdk.targetsize-24.png"
    "../res/Tiles/SmallTile-sdk.targetsize-256.png"
    "../res/Tiles/SmallTile-sdk.targetsize-30.png"
    "../res/Tiles/SmallTile-sdk.targetsize-32.png"
    "../res/Tiles/SmallTile-sdk.targetsize-36.png"
    "../res/Tiles/SmallTile-sdk.targetsize-40.png"
    "../res/Tiles/SmallTile-sdk.targetsize-48.png"
    "../res/Tiles/SmallTile-sdk.targetsize-60.png"
    "../res/Tiles/SmallTile-sdk.targetsize-64.png"
    "../res/Tiles/SmallTile-sdk.targetsize-72.png"
    "../res/Tiles/SmallTile-sdk.targetsize-80.png"
    "../res/Tiles/SmallTile-sdk.targetsize-96.png"
    "../res/Tiles/SmallTile.scale-100.png"
    "../res/Tiles/SmallTile.scale-125.png"
    "../res/Tiles/SmallTile.scale-150.png"
    "../res/Tiles/SmallTile.scale-200.png"
    "../res/Tiles/SmallTile.scale-400.png"
    "../res/Tiles/splash-sdk.scale-100.png"
    "../res/Tiles/splash-sdk.scale-125.png"
    "../res/Tiles/splash-sdk.scale-150.png"
    "../res/Tiles/splash-sdk.scale-200.png"
    "../res/Tiles/splash-sdk.scale-400.png"
    "../res/Tiles/squaretile-sdk.scale-100.png"
    "../res/Tiles/squaretile-sdk.scale-125.png"
    "../res/Tiles/squaretile-sdk.scale-150.png"
    "../res/Tiles/squaretile-sdk.scale-200.png"
    "../res/Tiles/squaretile-sdk.scale-400.png"
    "../res/Tiles/StoreLogo-sdk.scale-100.png"
    "../res/Tiles/StoreLogo-sdk.scale-125.png"
    "../res/Tiles/StoreLogo-sdk.scale-150.png"
    "../res/Tiles/StoreLogo-sdk.scale-200.png"
    "../res/Tiles/StoreLogo-sdk.scale-400.png"
    "../res/Tiles/Tile_General.png"
    "../res/Tiles/TitlebarLogo.png"
    "../res/Tiles/widelogo.scale-100.png"
    "../res/Tiles/widelogo.scale-140.png"
    "../res/Tiles/widelogo.scale-180.png"
    "../res/Tiles/WideLogo.scale-80.png"
    "../res/Tiles/WideTile.scale-100.png"
    "../res/Tiles/WideTile.scale-125.png"
    "../res/Tiles/WideTile.scale-150.png"
    "../res/Tiles/WideTile.scale-200.png"
    "../res/Tiles/WideTile.scale-400.png"
    "../res/Typography.dark.png"
    "../res/Typography.light.png"
    "../res/widelogo.scale-100.png"
    "../res/widelogo.scale-140.png"
    "../res/widelogo.scale-180.png"
    "../res/WideLogo.scale-80.png"
    # "../res/Segoe_Fluent_Icons.ttf"
    "../res/ControlResImages/GradientColor.png"
)
source_group(TREE ${CMAKE_SOURCE_DIR} FILES ${RES_FILES})

qt_add_resources(${TGT} "ControlsRes"
PREFIX "/"
BASE ".."
FILES
${RES_FILES}
)
flu_qrc_lowopt(ControlsRes)

set(I18N_FILES
    "../i18n/Controls.en-US.qm"
    "../i18n/Controls.zh-CN.qm"
)

source_group(TREE ${CMAKE_SOURCE_DIR} FILES ${I18N_FILES})

qt_add_resources(${TGT} "ControlsI18n"
    PREFIX "/"
    BASE ".."
    FILES
    ${I18N_FILES}
)
flu_qrc_lowopt(ControlsI18n)

else()
target_sources(${TGT} PUBLIC "ControlsQss.qrc" "ControlsRes.qrc" "ControlsI18n.qrc")
endif() ### end for qt version.


endif() #### end for use_qrc;

if (USE_QRC)
    add_definitions(-DUSE_QRC)
endif()


if(QT_VERSION VERSION_GREATER_EQUAL "6.2")
target_link_libraries(${TGT}
    PUBLIC
    framelesshelper
    FluentUI::Utils
    qwindowkit
    Qt${QT_VERSION_MAJOR}::Core5Compat
    cmark
    qscintilla
    qtadvanceddocking-qt6
)
else()
target_link_libraries(${TGT}
    PUBLIC
    framelesshelper
    FluentUI::Utils
    qwindowkit
    cmark
    qscintilla
    qtadvanceddocking-qt5
)
endif()

add_library(FluentUI::Controls ALIAS ${TGT})
